// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3GlplrD-2lV6AWbrAqFlmVfgKOo-bvs0',
    appId: '1:741151910832:android:1f49251034387d717d4475',
    messagingSenderId: '741151910832',
    projectId: 'redhat-administrator',
    storageBucket: 'redhat-administrator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjzbPqcLTRctWbY9p7cOb4Qj1_KePfT8c',
    appId: '1:741151910832:ios:0a884e978bd595bc7d4475',
    messagingSenderId: '741151910832',
    projectId: 'redhat-administrator',
    storageBucket: 'redhat-administrator.appspot.com',
    iosClientId: '741151910832-agep0q6c4bbtjjptetis7nuejq3rcehe.apps.googleusercontent.com',
    iosBundleId: 'com.example.appV2',
  );
}
